### ISSUE TITLE
请问有做代理池吗，换不同的ip

### ISSUE THREAD

**Issue by x1737886903** [Homby/WJX_AutoSubmit#1]
感谢大佬

**Comment by x1737886903** [comment]
**********  Version : 1.0.0  **********
提交状态404
停止 16 秒

**Comment by Homby** [comment]
啊这，过年回家了，还没时间更新

**Comment by Homby** [comment]
目前还不能完全实现自动化😭

**Comment by x1737886903** [comment]
> 目前还不能完全实现自动化😭

哦哦，请问下我为啥会提示404呢

**Comment by Homby** [comment]
问卷失效了，我这几天更新一下吧

**Comment by Homby** [comment]
如果你急需刷问卷量，我可以先帮你刷好，然后我有时间再更新，扣扣449213088希望能够帮到你🌹
